config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

profile: "jaffle_shop"

# Most important artefact types
model-paths: ["models"]
test-paths: ["data-tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
# Other artefact types
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "Australia/Melbourne"

seeds:
  jaffle_shop:
    +schema: jaffle_shop_demo
    +docs:
      node_color: "#b1560f"

models:
  jaffle_shop:
    staging:
      +materialized: view
      +docs:
        node_color: "#71706e"
    marts:
      +materialized: table
      +docs:
        node_color: "#d3a108"
